language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libgtest-dev
  - sudo apt-get install -y -qq libsdl2-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build .
after_success:
  - cd build && ./Chip8_tests

notifications:
  email: false
