# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

step-install-deps: &step-install-deps
  run:
    name: Install project dependencies
    command: |
      apt update
      apt install -y cmake libsdl2-dev
      git submodule init
      git submodule update

#checkout:
#  post:
#    - git submodule init
#    - git submodule update

step-test: &step-test
  run:
    name: Perform tests
    parameters:
      docker_image:
        description: "Sample desc"
        default: "hello world"
        type: string
    command: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug ..
      cmake --build .
      echo "ASDF" << parameters.docker_image >>
      ./Chip8_tests

jobs:
  perform_test:
    docker:
      - image: gcc:8.2
    resource_class: small
    steps:
      - checkout
      - *step-install-deps
      - *step-test

workflows:
  build-linux:
    jobs:
       - perform_test
