# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
step-install-deps: &step-install-deps
  run:
    name: Install project dependencies
    command: |
      exit 1

#libsdl2-dev cmake libgtest-dev
#sudo cp -a libgtest_main.so libgtest.so /usr/lib/
#mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . && ./Chip8_tests
#libsdl2-dev cmake libgtest-dev

step-test: &step-test
  run:
    name: Perform tests
    command: |
      exit 1

version: 2
jobs:
  step-install-deps:
    docker:
      - image: gcc:8.2
    resource_class: small
    steps:
      - checkout
      - *step-build
      - *step-test

workflows:
  version: 2
  build-linux:
    jobs:
       - step-test
          requires:
            - step-install-deps